"AgeOfCedrick" : "{\"name\":\"AgeOfCedrick\",\"type\":\"org.ff4j.property.PropertyString\",\"description\":\"null\",\"value\":\"hamza\"}"
"featureValidate" : "{\"uid\":\"featureValidate\",\"enable\":true}"
